### ISSUE TITLE
Suggestion: Client Library

### ISSUE THREAD

**Issue by cklmercer** [feathersjs/feathers-permissions#13]
I am suggesting that there should client library for this module, so that we can do conditional rendering/routing/etc without have to make service requests.

After authentication I cache a subset of the current user's data, including their permissions. I would like to do some conditional rendering/routing based on those permissions.

**Comment by daffl** [comment]
I don't see a reason we couldn't make a Browserified build for this. The only dependencies are `debug` and `feathers-errors` which both work on the client.
