### ISSUE TITLE
README says this "will go out by Nov. 21st."

### ISSUE THREAD

**Issue by IBwWG** [feathersjs/feathers-permissions#14]

**Comment by mattiasewers** [comment]
Yeah I am also waiting for this...

**Comment by marshallswain** [comment]
@IBwWG Thanks for pointing this out.  I've removed the date from the README.md.  Unfortunately it doesn't help the problem of waiting on this to land.

Between an ambitious release, a new baby, moving, a home purchase, and the Holidays, we've been all been pretty occupied.

**Comment by IBwWG** [comment]
Wow, go team!  No worries, life happens and congrats on all the big changes!
