### ISSUE TITLE
No file naming conventions

### ISSUE THREAD

**Issue by elfey** [feathersjs/feathers-permissions#19]
https://github.com/feathersjs/feathers-permissions/tree/master/src/hooks

If you take a quick look at the file naming conventions there, they differ.

I'm wondering if there's a reason for this, or if it's just arbitrary.

**Comment by marshallswain** [comment]
It's just not finished, yet.

**Comment by ekryski** [comment]
This has been fixed in the filters branch, which is just about to get an update and merge.
