### ISSUE TITLE
"This module is not published yet"

### ISSUE THREAD

**Issue by leebenson** [feathersjs/feathers-permissions#8]
it's available now, right?

**Comment by marshallswain** [comment]
Yup.  Time to remove that message and republish

**Comment by daffl** [comment]
@ekryski Can you add the team as collaborators on npm for all those new repositories? I was quickly going to change it but I'm not allowed to publish.

**Comment by ekryski** [comment]
Ya for sure. Man I wish that was easier. I don't even remember everyone's handles

**Comment by ekryski** [comment]
And yes it is available. I have some more changes coming today. Just wrapping up tests and docs.

**Comment by ekryski** [comment]
It's published. Closing.

**Comment by daffl** [comment]
@ekryski  Don't we still need to change the big fat warning in the Readme and re-publish to NPM?

**Comment by ekryski** [comment]
Ya but I have changes coming today. Will do it this afternoon.
